// Generated by build-daily.js. Do not edit by hand.
// Verses: text_uthmani, Turkish (Diyanet İşleri, quran.com #77), English (Saheeh International, #20)
// and an excerpt of the Arabic Tafsir Ibn Kathir (#14), all from api.quran.com.
// Hadiths: al-Nawawi's Forty Hadith (Arabic, English, Turkish) from github.com/fawazahmed0/hadith-api.
const DAILY_VERSES = [
 {
  "key": "93:3",
  "arabic": "مَا وَدَّعَكَ رَبُّكَ وَمَا قَلَىٰ",
  "tr": "Rabbin seni ne bıraktı ve ne de sana darıldı.",
  "en": "Your Lord has not taken leave of you, [O Muḥammad], nor has He detested [you].",
  "tafsir": "وقد ذكر بعض السلف منهم ابن إسحاق أن هذه السورة هي التي أوحاها جبريل إلى رسول الله صلى الله عليه وسلم حين تبدى له في صورته التى خلقه الله عليها ودنا إليه وتدلى منهبطا عليه وهو بالأبطح \"فأوحى إلى عبده ما أوحى\" قال: قال له هذه السورة \"والضحى والليل إذا سجى\" قال العوفي عن ابن عباس: لما نزل على رسول الله صلى الله عليه وسلم القرآن أبطأ عنه جبريل أياما فتغير بذلك فقال المشركون ودعه ربه وقلاه فأنزل الله \"ما ودعك ربك وما …",
  "source_tr": "Duhâ Sûresi, 3. âyet",
  "source_en": "Surah Ad-Duhaa, 93:3",
  "source_ar": "سورة الضحى، الآية 3"
 },
 {
  "key": "13:28",
  "arabic": "ٱلَّذِينَ ءَامَنُوا۟ وَتَطْمَئِنُّ قُلُوبُهُم بِذِكْرِ ٱللَّهِ ۗ أَلَا بِذِكْرِ ٱللَّهِ تَطْمَئِنُّ ٱلْقُلُوبُ",
  "tr": "Onlar inanmışlar, kalbleri Allah'ı anmakla huzura kavuşmuştur. Dikkat edin, kalbler ancak Allah'ı anmakla huzura kavuşur.",
  "en": "Those who have believed and whose hearts are assured by the remembrance of Allāh. Unquestionably, by the remembrance of Allāh hearts are assured.\"",
  "tafsir": "الذين آمنوا وتطمئن قلوبهم بذكر الله ) أي : تطيب وتركن إلى جانب الله ، وتسكن عند ذكره ، وترضى به مولى ونصيرا; ولهذا قال : ( ألا بذكر الله تطمئن القلوب ) أي : هو حقيق بذلك .",
  "source_tr": "Ra'd Sûresi, 28. âyet",
  "source_en": "Surah Ar-Ra'd, 13:28",
  "source_ar": "سورة الرعد، الآية 28"
 },
 {
  "key": "14:7",
  "arabic": "وَإِذْ تَأَذَّنَ رَبُّكُمْ لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ ۖ وَلَئِن كَفَرْتُمْ إِنَّ عَذَابِى لَشَدِيدٌ",
  "tr": "Rabbiniz: \"Şükrederseniz and olsun ki, size karşılığını artıracağım; nankörlük ederseniz bilin ki azabım pek çetindir\" diye bildirmişti.",
  "en": "And [remember] when your Lord proclaimed, 'If you are grateful, I will surely increase you [in favor]; but if you deny, indeed, My punishment is severe.'\"",
  "tafsir": "وقوله : ( وإذ تأذن ربكم ) أي : آذنكم وأعلمكم بوعده لكم . ويحتمل أن يكون المعنى : وإذ أقسم ربكم وآلى بعزته وجلاله وكبريائه كما قال : ( وإذ تأذن ربك ليبعثن عليهم إلى يوم القيامة [ من يسومهم سوء العذاب ] ) [ الأعراف : 167 ] . وقوله ( لئن شكرتم لأزيدنكم ) أي : لئن شكرتم نعمتي عليكم لأزيدنكم منها ، ( ولئن كفرتم ) أي : كفرتم النعم وسترتموها وجحدتموها ، ( إن عذابي لشديد ) وذلك بسلبها عنهم ، وعقابه إياهم على كفرها . …",
  "source_tr": "İbrâhîm Sûresi, 7. âyet",
  "source_en": "Surah Ibrahim, 14:7",
  "source_ar": "سورة ابراهيم، الآية 7"
 },
 {
  "key": "2:153",
  "arabic": "يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ ٱسْتَعِينُوا۟ بِٱلصَّبْرِ وَٱلصَّلَوٰةِ ۚ إِنَّ ٱللَّهَ مَعَ ٱلصَّـٰبِرِينَ",
  "tr": "Ey İnananlar! Sabır ve namazla yardım dileyin. Allah, muhakkak ki sabredenlerle beraberdir.",
  "en": "O you who have believed, seek help through patience and prayer. Indeed, Allāh is with the patient.",
  "tafsir": "لما فرغ تعالى من بيان الأمر بالشكر شرع في بيان الصبر ، والإرشاد إلى الاستعانة بالصبر والصلاة ، فإن العبد إما أن يكون في نعمة فيشكر عليها ، أو في نقمة فيصبر عليها ; كما جاء في الحديث : \" عجبا للمؤمن ، لا يقضي الله له قضاء إلا كان خيرا له : إن أصابته سراء ، فشكر ، كان خيرا له ; وإن أصابته ضراء فصبر كان خيرا له \" . …",
  "source_tr": "Bakara Sûresi, 153. âyet",
  "source_en": "Surah Al-Baqarah, 2:153",
  "source_ar": "سورة البقرة، الآية 153"
 },
 {
  "key": "2:152",
  "arabic": "فَٱذْكُرُونِىٓ أَذْكُرْكُمْ وَٱشْكُرُوا۟ لِى وَلَا تَكْفُرُونِ",
  "tr": "Artık Beni anın, Ben de sizi anayım; Bana şükredin, nankörlük etmeyin.",
  "en": "So remember Me; I will remember you. And be grateful to Me and do not deny Me.",
  "tafsir": "فاذكروني أذكركم واشكروا لي ولا تكفرون ) . قال مجاهد في قوله : ( كما أرسلنا فيكم رسولا منكم ) يقول : كما فعلت فاذكروني . قال عبد الله بن وهب ، عن هشام بن سعيد ، عن زيد بن أسلم : أن موسى ، عليه السلام ، قال : يا رب ، كيف أشكرك ؟ قال له ربه : تذكرني ولا تنساني ، فإذا ذكرتني فقد شكرتني ، وإذا نسيتني فقد كفرتني . …",
  "source_tr": "Bakara Sûresi, 152. âyet",
  "source_en": "Surah Al-Baqarah, 2:152",
  "source_ar": "سورة البقرة، الآية 152"
 },
 {
  "key": "3:139",
  "arabic": "وَلَا تَهِنُوا۟ وَلَا تَحْزَنُوا۟ وَأَنتُمُ ٱلْأَعْلَوْنَ إِن كُنتُم مُّؤْمِنِينَ",
  "tr": "Gevşemeyin, üzülmeyin, inanmışsanız, mutlaka siz en üstünsünüzdür.",
  "en": "So do not weaken and do not grieve, and you will be superior if you are [true] believers.",
  "tafsir": "ثم قال مسليا للمؤمنين : ( ولا تهنوا ) أي : لا تضعفوا بسبب ما جرى ( ولا تحزنوا وأنتم الأعلون إن كنتم مؤمنين ) أي العاقبة والنصرة لكم أيها المؤمنون .",
  "source_tr": "Âl-i İmrân Sûresi, 139. âyet",
  "source_en": "Surah Ali 'Imran, 3:139",
  "source_ar": "سورة آل عمران، الآية 139"
 },
 {
  "key": "29:69",
  "arabic": "وَٱلَّذِينَ جَـٰهَدُوا۟ فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا ۚ وَإِنَّ ٱللَّهَ لَمَعَ ٱلْمُحْسِنِينَ",
  "tr": "Ama Bizim uğrumuzda cihat edenleri elbette yollarımıza eriştireceğiz. Allah şüphesiz, iyi davrananlarla beraberdir.",
  "en": "And those who strive for Us - We will surely guide them to Our ways. And indeed, Allāh is with the doers of good.",
  "tafsir": "ثم قال ( والذين جاهدوا فينا ) يعني : الرسول ، صلوات الله وسلامه عليه ، وأصحابه وأتباعه إلى يوم الدين ( لنهدينهم سبلنا ) ، أي : لنبصرنهم سبلنا ، أي : طرقنا في الدنيا والآخرة . قال ابن أبي حاتم : حدثنا أبي ، حدثنا أحمد بن أبي الحواري ، حدثنا عباس الهمداني أبو أحمد - من أهل عكا - في قول الله : ( والذين جاهدوا فينا لنهدينهم سبلنا وإن الله لمع المحسنين ) قال : الذين يعملون بما يعلمون ، يهديهم لما لا يعلمون . …",
  "source_tr": "Ankebût Sûresi, 69. âyet",
  "source_en": "Surah Al-'Ankabut, 29:69",
  "source_ar": "سورة العنكبوت، الآية 69"
 },
 {
  "key": "39:53",
  "arabic": "۞ قُلْ يَـٰعِبَادِىَ ٱلَّذِينَ أَسْرَفُوا۟ عَلَىٰٓ أَنفُسِهِمْ لَا تَقْنَطُوا۟ مِن رَّحْمَةِ ٱللَّهِ ۚ إِنَّ ٱللَّهَ يَغْفِرُ ٱلذُّنُوبَ جَمِيعًا ۚ إِنَّهُۥ هُوَ ٱلْغَفُورُ ٱلرَّحِيمُ",
  "tr": "De ki: \"Ey kendilerine kötülük edip aşırı giden kullarım! Allah'ın rahmetinden umudunuzu kesmeyin. Doğrusu Allah günahların hepsini bağışlar. Çünkü O, bağışlayandır, merhametlidir.\"",
  "en": "Say, \"O My servants who have transgressed against themselves [by sinning], do not despair of the mercy of Allāh. Indeed, Allāh forgives all sins. Indeed, it is He who is the Forgiving, the Merciful.\"",
  "tafsir": "هذه الآية الكريمة دعوة لجميع العصاة من الكفرة وغيرهم إلى التوبة والإنابة ، وإخبار بأن الله يغفر الذنوب جميعا لمن تاب منها ورجع عنها ، وإن كانت مهما كانت وإن كثرت وكانت مثل زبد البحر . ولا يصح حمل هذه [ الآية ] على غير توبة ; لأن الشرك لا يغفر لمن لم يتب منه . …",
  "source_tr": "Zümer Sûresi, 53. âyet",
  "source_en": "Surah Az-Zumar, 39:53",
  "source_ar": "سورة الزمر، الآية 53"
 },
 {
  "key": "20:114",
  "arabic": "فَتَعَـٰلَى ٱللَّهُ ٱلْمَلِكُ ٱلْحَقُّ ۗ وَلَا تَعْجَلْ بِٱلْقُرْءَانِ مِن قَبْلِ أَن يُقْضَىٰٓ إِلَيْكَ وَحْيُهُۥ ۖ وَقُل رَّبِّ زِدْنِى عِلْمًا",
  "tr": "Gerçek hükümdar olan Allah Yüce'dir. Kuran sana vahyedilirken, vahy bitmezden önce, unutmamak için, tekrarda acele edip durma, \"Rabbim! ilmimi artır\" de.",
  "en": "So high [above all] is Allāh, the Sovereign, the Truth. And, [O Muḥammad], do not hasten with [recitation of] the Qur’ān before its revelation is completed to you, and say, \"My Lord, increase me in knowledge.\"",
  "tafsir": "وقوله : ( ولا تعجل بالقرآن من قبل أن يقضى إليك وحيه ) كقوله تعالى في سورة \" لا أقسم بيوم القيامة \" ( لا تحرك به لسانك لتعجل به إن علينا جمعه وقرآنه فإذا قرأناه فاتبع قرآنه ثم إن علينا بيانه ) [ القيامة : 16 - 19 ] ، وثبت في الصحيح عن ابن عباس ; أن رسول الله صلى الله عليه وسلم كان يعالج من الوحي شدة ، فكان مما يحرك لسانه ، فأنزل الله هذه الآية يعني : أنه ، عليه السلام ، كان إذا جاءه جبريل بالوحي ، كلما قال جبريل آية …",
  "source_tr": "Tâhâ Sûresi, 114. âyet",
  "source_en": "Surah Taha, 20:114",
  "source_ar": "سورة طه، الآية 114"
 },
 {
  "key": "16:97",
  "arabic": "مَنْ عَمِلَ صَـٰلِحًا مِّن ذَكَرٍ أَوْ أُنثَىٰ وَهُوَ مُؤْمِنٌ فَلَنُحْيِيَنَّهُۥ حَيَوٰةً طَيِّبَةً ۖ وَلَنَجْزِيَنَّهُمْ أَجْرَهُم بِأَحْسَنِ مَا كَانُوا۟ يَعْمَلُونَ",
  "tr": "Kadın, erkek, inanmış olarak kim iyi iş işlerse, ona hoş bir hayat yaşatacağız. Ecirlerini yaptıklarından daha güzeli ile ödeyeceğiz.",
  "en": "Whoever does righteousness, whether male or female, while he is a believer - We will surely cause him to live a good life, and We will surely give them their reward [in the Hereafter] according to the best of what they used to do.",
  "tafsir": "هذا وعد من الله تعالى لمن عمل صالحا - وهو العمل المتابع لكتاب الله تعالى وسنة نبيه من ذكر أو أنثى من بني آدم ، وقلبه مؤمن بالله ورسوله ، وإن هذا العمل المأمور به مشروع من عند الله - بأن يحييه الله حياة طيبة في الدنيا وأن يجزيه بأحسن ما عمله في الدار الآخرة . والحياة الطيبة تشمل وجوه الراحة من أي جهة كانت . وقد روي عن ابن عباس وجماعة أنهم فسروها بالرزق الحلال الطيب . …",
  "source_tr": "Nahl Sûresi, 97. âyet",
  "source_en": "Surah An-Nahl, 16:97",
  "source_ar": "سورة النحل، الآية 97"
 },
 {
  "key": "50:16",
  "arabic": "وَلَقَدْ خَلَقْنَا ٱلْإِنسَـٰنَ وَنَعْلَمُ مَا تُوَسْوِسُ بِهِۦ نَفْسُهُۥ ۖ وَنَحْنُ أَقْرَبُ إِلَيْهِ مِنْ حَبْلِ ٱلْوَرِيدِ",
  "tr": "And olsun ki insanı Biz yarattık; nefsinin kendisine fısıldadıklarını biliriz; Biz ona şah damarından daha yakınız.",
  "en": "And We have already created man and know what his soul whispers to him, and We are closer to him than [his] jugular vein.",
  "tafsir": "يخبر تعالى عن قدرته على الإنسان بأنه خالقه ، وعمله محيط بجميع أموره حتى إنه تعالى يعلم ما توسوس به نفوس بني آدم من الخير والشر . وقد ثبت في الصحيح عن رسول الله - صلى الله عليه وسلم - أنه قال : \" إن الله تجاوز لأمتي ما حدثت به أنفسها ما لم تقل أو تعمل \" . وقوله : ( ونحن أقرب إليه من حبل الوريد ) يعني : ملائكته تعالى أقرب إلى الإنسان من حبل وريده إليه . …",
  "source_tr": "Kâf Sûresi, 16. âyet",
  "source_en": "Surah Qaf, 50:16",
  "source_ar": "سورة ق، الآية 16"
 },
 {
  "key": "3:200",
  "arabic": "يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ ٱصْبِرُوا۟ وَصَابِرُوا۟ وَرَابِطُوا۟ وَٱتَّقُوا۟ ٱللَّهَ لَعَلَّكُمْ تُفْلِحُونَ",
  "tr": "Ey İnananlar! Sabredin, düşmanlarınızdan daha sabırlı olun, cihada hazır bulunun, Allah'a karşı gelmekten sakının ki başarıya erişebilesiniz.",
  "en": "O you who have believed, persevere and endure and remain stationed and fear Allāh that you may be successful.",
  "tafsir": "وقوله : ( يا أيها الذين آمنوا اصبروا وصابروا ورابطوا ) قال الحسن البصري ، رحمه الله : أمروا أن يصبروا على دينهم الذي ارتضاه الله لهم ، وهو الإسلام ، فلا يدعوه لسراء ولا لضراء ولا لشدة ولا لرخاء ، حتى يموتوا مسلمين ، وأن يصابروا الأعداء الذين يكتمون دينهم . وكذلك قال غير واحد من علماء السلف . وأما المرابطة فهي المداومة في مكان العبادة والثبات . …",
  "source_tr": "Âl-i İmrân Sûresi, 200. âyet",
  "source_en": "Surah Ali 'Imran, 3:200",
  "source_ar": "سورة آل عمران، الآية 200"
 },
 {
  "key": "18:46",
  "arabic": "ٱلْمَالُ وَٱلْبَنُونَ زِينَةُ ٱلْحَيَوٰةِ ٱلدُّنْيَا ۖ وَٱلْبَـٰقِيَـٰتُ ٱلصَّـٰلِحَـٰتُ خَيْرٌ عِندَ رَبِّكَ ثَوَابًا وَخَيْرٌ أَمَلًا",
  "tr": "Mal ve oğullar, dünya hayatının süsüdür. Ama baki kalacak yararlı işler, sevab olarak da, emel olarak da, Rabbinin katında daha hayırlıdır.",
  "en": "Wealth and children are [but] adornment of the worldly life. But the enduring good deeds are better to your Lord for reward and better for [one's] hope.",
  "tafsir": "وقوله : ( المال والبنون زينة الحياة الدنيا ) كقوله ( زين للناس حب الشهوات من النساء والبنين والقناطير المقنطرة من الذهب والفضة والخيل المسومة والأنعام والحرث ذلك متاع الحياة الدنيا والله عنده حسن المآب ) [ آل عمران : 14 ] ، وقال تعالى : ( إنما أموالكم وأولادكم فتنة والله عنده أجر عظيم ) [ التغابن : 15 ] أي : الإقبال عليه والتفرغ لعبادته ، خير لكم من اشتغالكم بهم والجمع لهم ، والشفقة المفرطة عليهم ؛ ولهذا قال : ( …",
  "source_tr": "Kehf Sûresi, 46. âyet",
  "source_en": "Surah Al-Kahf, 18:46",
  "source_ar": "سورة الكهف، الآية 46"
 },
 {
  "key": "23:1",
  "arabic": " قَدْ أَفْلَحَ ٱلْمُؤْمِنُونَ",
  "tr": "Müminler saadete ermişlerdir.",
  "en": "Certainly will the believers have succeeded:",
  "tafsir": "قد أفلح المؤمنون ) حتى ختم العشر . وكذا روى الترمذي في تفسيره ، والنسائي في الصلاة ، من حديث عبد الرزاق ، به . وقال الترمذي : منكر ، لا نعرف أحدا رواه غير يونس بن سليم ، ويونس لا نعرفه . وقال النسائي في تفسيره : أنبأنا قتيبة بن سعيد ، حدثنا جعفر ، عن أبي عمران عن يزيد بن بابنوس قال : قلنا لعائشة : يا أم المؤمنين ، كيف كان خلق رسول الله صلى الله عليه وسلم؟ …",
  "source_tr": "Mü'minûn Sûresi, 1. âyet",
  "source_en": "Surah Al-Mu'minun, 23:1",
  "source_ar": "سورة المؤمنون، الآية 1"
 },
 {
  "key": "103:3",
  "arabic": "إِلَّا ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّـٰلِحَـٰتِ وَتَوَاصَوْا۟ بِٱلْحَقِّ وَتَوَاصَوْا۟ بِٱلصَّبْرِ",
  "tr": "Ancak inanıp yararlı iş işleyenler, birbirlerine gerçeği tavsiye edenler ve sabırlı olmayı tavsiye edenler bunun dışındadır.",
  "en": "Except for those who have believed and done righteous deeds and advised each other to truth and advised each other to patience.",
  "tafsir": "فاستثنى من جنس الإنسان عن الخسران الذين آمنوا بقلوبهم وعملوا الصالحات بجوارحهم \" وتواصوا بالحق \" وهو أداء الطاعات وترك المحرمات.",
  "source_tr": "Asr Sûresi, 3. âyet",
  "source_en": "Surah Al-'Asr, 103:3",
  "source_ar": "سورة العصر، الآية 3"
 },
 {
  "key": "7:56",
  "arabic": "وَلَا تُفْسِدُوا۟ فِى ٱلْأَرْضِ بَعْدَ إِصْلَـٰحِهَا وَٱدْعُوهُ خَوْفًا وَطَمَعًا ۚ إِنَّ رَحْمَتَ ٱللَّهِ قَرِيبٌ مِّنَ ٱلْمُحْسِنِينَ",
  "tr": "Düzeltilmişken, yeryüzünde bozgunculuk yapmayın. Allah'a korkarak ve umutla yalvarın. Doğrusu Allah'ın rahmeti iyi davrananlara yakındır.",
  "en": "And cause not corruption upon the earth after its reformation. And invoke Him in fear and aspiration. Indeed, the mercy of Allāh is near to the doers of good.",
  "tafsir": "وقوله تعالى : ( ولا تفسدوا في الأرض بعد إصلاحها ) ينهى تعالى عن الإفساد في الأرض ، وما أضره بعد الإصلاح ! فإنه إذا كانت الأمور ماشية على السداد ، ثم وقع الإفساد بعد ذلك ، كان أضر ما يكون على العباد . فنهى الله تعالى عن ذلك ، وأمر بعبادته ودعائه والتضرع إليه والتذلل لديه ، فقال : ( وادعوه خوفا وطمعا ) أي : خوفا مما عنده من وبيل العقاب ، وطمعا فيما عنده من جزيل الثواب . …",
  "source_tr": "A'râf Sûresi, 56. âyet",
  "source_en": "Surah Al-A'raf, 7:56",
  "source_ar": "سورة الأعراف، الآية 56"
 },
 {
  "key": "25:63",
  "arabic": "وَعِبَادُ ٱلرَّحْمَـٰنِ ٱلَّذِينَ يَمْشُونَ عَلَى ٱلْأَرْضِ هَوْنًا وَإِذَا خَاطَبَهُمُ ٱلْجَـٰهِلُونَ قَالُوا۟ سَلَـٰمًا",
  "tr": "Rahman'ın kulları yeryüzünde mütevazı yürürler. Bilgisizler kendilerine takıldıkları zaman onlara güzel ve yumuşak söz söylerler.",
  "en": "And the servants of the Most Merciful are those who walk upon the earth easily, and when the ignorant address them [harshly], they say [words of] peace,",
  "tafsir": "هذه صفات عباد الله المؤمنين ( الذين يمشون على الأرض هونا ) أي : بسكينة ووقار من غير جبرية ولا استكبار ، كما قال : ( ولا تمش في الأرض مرحا إنك لن تخرق الأرض ولن تبلغ الجبال طولا ) [ الإسراء : 37 ] . فأما هؤلاء فإنهم يمشون من غير استكبار ولا مرح ، ولا أشر ولا بطر ، وليس المراد أنهم يمشون كالمرضى من التصانع تصنعا ورياء ، فقد كان سيد ولد آدم صلى الله عليه وسلم إذا مشى كأنما ينحط من صبب ، وكأنما الأرض تطوى له . …",
  "source_tr": "Furkân Sûresi, 63. âyet",
  "source_en": "Surah Al-Furqan, 25:63",
  "source_ar": "سورة الفرقان، الآية 63"
 },
 {
  "key": "31:17",
  "arabic": "يَـٰبُنَىَّ أَقِمِ ٱلصَّلَوٰةَ وَأْمُرْ بِٱلْمَعْرُوفِ وَٱنْهَ عَنِ ٱلْمُنكَرِ وَٱصْبِرْ عَلَىٰ مَآ أَصَابَكَ ۖ إِنَّ ذَٰلِكَ مِنْ عَزْمِ ٱلْأُمُورِ",
  "tr": "\"Ey oğulcuğum! Namazı kıl, uygun olanı buyurup fenalığı önle, başına gelene sabret; doğrusu bunlar, azmedilmeğe değer işlerdir.\"",
  "en": "O my son, establish prayer, enjoin what is right, forbid what is wrong, and be patient over what befalls you. Indeed, [all] that is of the matters [requiring] resolve.",
  "tafsir": "قال : ( يا بني أقم الصلاة ) أي : بحدودها وفروضها وأوقاتها ، ( وأمر بالمعروف وانه عن المنكر ) أي : بحسب طاقتك وجهدك ، ( واصبر على ما أصابك ) ، علم أن الآمر بالمعروف والناهي عن المنكر ، لا بد أن يناله من الناس أذى ، فأمره بالصبر . وقوله : ( إن ذلك من عزم الأمور ) أي : إن الصبر على أذى الناس لمن عزم الأمور .",
  "source_tr": "Lokmân Sûresi, 17. âyet",
  "source_en": "Surah Luqman, 31:17",
  "source_ar": "سورة لقمان، الآية 17"
 },
 {
  "key": "64:16",
  "arabic": "فَٱتَّقُوا۟ ٱللَّهَ مَا ٱسْتَطَعْتُمْ وَٱسْمَعُوا۟ وَأَطِيعُوا۟ وَأَنفِقُوا۟ خَيْرًا لِّأَنفُسِكُمْ ۗ وَمَن يُوقَ شُحَّ نَفْسِهِۦ فَأُو۟لَـٰٓئِكَ هُمُ ٱلْمُفْلِحُونَ",
  "tr": "Allah'a karşı gelmekten gücünüzün yettiği kadar sakının, buyruklarını dinleyin, itaat edin; kendinizin iyiliğine olarak mallarınızdan sarfedin; nefsinin tamahkarlığından korunan kimseler, işte onlar saadete erenlerdir.",
  "en": "So fear Allāh as much as you are able and listen and obey and spend [in the way of Allāh]; it is better for your selves. And whoever is protected from the stinginess of his soul - it is those who will be the successful.",
  "tafsir": "وقوله تعالى : ( فاتقوا الله ما استطعتم ) أي : جهدكم وطاقتكم . كما ثبت في الصحيحين عن أبي هريرة رضي الله عنه ، قال : قال رسول الله - صلى الله عليه وسلم - : \" إذا أمرتكم بأمر فائتوا منه ما استطعتم ، وما نهيتكم عنه فاجتنبوه \" وقد قال بعض المفسرين - كما رواه مالك ، عن زيد بن أسلم - إن هذه الآية العظيمة ناسخة للتي في \" آل عمران \" وهي قوله : ( ياأيها الذين آمنوا اتقوا الله حق تقاته ولا تموتن إلا وأنتم مسلمون ) [ آل عمران …",
  "source_tr": "Teğâbün Sûresi, 16. âyet",
  "source_en": "Surah At-Taghabun, 64:16",
  "source_ar": "سورة التغابن، الآية 16"
 },
 {
  "key": "2:155",
  "arabic": "وَلَنَبْلُوَنَّكُم بِشَىْءٍ مِّنَ ٱلْخَوْفِ وَٱلْجُوعِ وَنَقْصٍ مِّنَ ٱلْأَمْوَٰلِ وَٱلْأَنفُسِ وَٱلثَّمَرَٰتِ ۗ وَبَشِّرِ ٱلصَّـٰبِرِينَ",
  "tr": "Muhakkak sizi biraz korku, biraz açlık ve mallardan, canlardan, ürünlerden biraz eksiltmekle deneriz, sabredenleri müjdele.",
  "en": "And We will surely test you with something of fear and hunger and a loss of wealth and lives and fruits, but give good tidings to the patient,",
  "tafsir": "أخبر تعالى أنه يبتلي عباده [ المؤمنين ] أي : يختبرهم ويمتحنهم ، كما قال تعالى : ( ولنبلونكم حتى نعلم المجاهدين منكم والصابرين ونبلو أخباركم ) [ محمد : 31 ] فتارة بالسراء ، وتارة بالضراء من خوف وجوع ، كما قال تعالى : ( فأذاقها الله لباس الجوع والخوف ) [ النحل : 112 ] فإن الجائع والخائف كل منهما يظهر ذلك عليه ; ولهذا قال : لباس الجوع والخوف . …",
  "source_tr": "Bakara Sûresi, 155. âyet",
  "source_en": "Surah Al-Baqarah, 2:155",
  "source_ar": "سورة البقرة، الآية 155"
 },
 {
  "key": "3:8",
  "arabic": "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً ۚ إِنَّكَ أَنتَ ٱلْوَهَّابُ",
  "tr": "Rabbimiz! Bizi doğru yola erdirdikten sonra kalblerimizi eğriltme, katından bize rahmet bağışla; şüphesiz Sen sonsuz bağışta bulunansın.",
  "en": "[Who say], \"Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy. Indeed, You are the Bestower.",
  "tafsir": "ثم قال تعالى عنهم مخبرا أنهم دعوا ربهم قائلين : ( ربنا لا تزغ قلوبنا بعد إذ هديتنا ) أي : لا تملها عن الهدى بعد إذ أقمتها عليه ولا تجعلنا كالذين في قلوبهم زيغ ، الذين يتبعون ما تشابه من القرآن ولكن ثبتنا على صراطك المستقيم ، ودينك القويم ( وهب لنا من لدنك ) أي : من عندك ) رحمة ) تثبت بها قلوبنا ، وتجمع بها شملنا ، وتزيدنا بها إيمانا وإيقانا ( إنك أنت الوهاب ) قال ابن أبي حاتم : حدثنا عمرو بن عبد الله الأودي - وقال …",
  "source_tr": "Âl-i İmrân Sûresi, 8. âyet",
  "source_en": "Surah Ali 'Imran, 3:8",
  "source_ar": "سورة آل عمران، الآية 8"
 },
 {
  "key": "2:201",
  "arabic": "وَمِنْهُم مَّن يَقُولُ رَبَّنَآ ءَاتِنَا فِى ٱلدُّنْيَا حَسَنَةً وَفِى ٱلْـَٔاخِرَةِ حَسَنَةً وَقِنَا عَذَابَ ٱلنَّارِ",
  "tr": "\"Rabbimiz! Bize dünyada iyiyi, ahirette de iyiyi ver, bizi ateşin azabından koru\" diyenler vardır.",
  "en": "But among them is he who says, \"Our Lord, give us in this world [that which is] good and in the Hereafter [that which is] good and protect us from the punishment of the Fire.\"",
  "tafsir": "فقال : ( ومنهم من يقول ربنا آتنا في الدنيا حسنة وفي الآخرة حسنة وقنا عذاب النار ) فجمعت هذه الدعوة كل خير في الدنيا ، وصرفت كل شر ، فإن الحسنة في الدنيا تشمل كل مطلوب دنيوي ، من عافية ، ودار رحبة ، وزوجة حسنة ، ورزق واسع ، وعلم نافع ، وعمل صالح ، ومركب هنيء ، وثناء جميل ، إلى غير ذلك مما اشتملت عليه عبارات المفسرين ، ولا منافاة بينها ، فإنها كلها مندرجة في الحسنة في الدنيا . …",
  "source_tr": "Bakara Sûresi, 201. âyet",
  "source_en": "Surah Al-Baqarah, 2:201",
  "source_ar": "سورة البقرة، الآية 201"
 },
 {
  "key": "6:162",
  "arabic": "قُلْ إِنَّ صَلَاتِى وَنُسُكِى وَمَحْيَاىَ وَمَمَاتِى لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ",
  "tr": "De ki: \"Namazım, ibadetlerim, hayatım ve ölümüm, alemlerin Rabbi Allah içindir.",
  "en": "Say, \"Indeed, my prayer, my rites of sacrifice, my living and my dying are for Allāh, Lord of the worlds.",
  "tafsir": "وقوله تعالى : ( قل إن صلاتي ونسكي ومحياي ومماتي لله رب العالمين ) يأمره تعالى أن يخبر المشركين الذين يعبدون غير الله ويذبحون لغير اسمه ، أنه مخالف لهم في ذلك ، فإن صلاته لله ونسكه على اسمه وحده لا شريك له ، وهذا كقوله تعالى : ( فصل لربك وانحر ) [ الكوثر : 2 ] أي : أخلص له صلاتك وذبيحتك ، فإن المشركين كانوا يعبدون الأصنام ويذبحون لها ، فأمره الله تعالى بمخالفتهم والانحراف عما هم فيه ، والإقبال بالقصد والنية والعزم …",
  "source_tr": "En'âm Sûresi, 162. âyet",
  "source_en": "Surah Al-An'am, 6:162",
  "source_ar": "سورة الأنعام، الآية 162"
 },
 {
  "key": "9:51",
  "arabic": "قُل لَّن يُصِيبَنَآ إِلَّا مَا كَتَبَ ٱللَّهُ لَنَا هُوَ مَوْلَىٰنَا ۚ وَعَلَى ٱللَّهِ فَلْيَتَوَكَّلِ ٱلْمُؤْمِنُونَ",
  "tr": "De ki: \"Allah'ın bize yazdığından başkası başımıza gelmez. O bizim Mevlamızdır, inananlar Allah'a güvensin.\"",
  "en": "Say, \"Never will we be struck except by what Allāh has decreed for us; He is our protector.\" And upon Allāh let the believers rely.",
  "tafsir": "فأرشد الله تعالى رسوله - صلوات الله وسلامه عليه - إلى جوابهم في عداوتهم هذه التامة ، فقال : ( قل ) أي : لهم ( لن يصيبنا إلا ما كتب الله لنا ) أي : نحن تحت مشيئة الله وقدره ، ( هو مولانا ) أي : سيدنا وملجؤنا ( وعلى الله فليتوكل المؤمنون ) أي : ونحن متوكلون عليه ، وهو حسبنا ونعم الوكيل .",
  "source_tr": "Tevbe Sûresi, 51. âyet",
  "source_en": "Surah At-Tawbah, 9:51",
  "source_ar": "سورة التوبة، الآية 51"
 },
 {
  "key": "20:25",
  "arabic": "قَالَ رَبِّ ٱشْرَحْ لِى صَدْرِى",
  "tr": "Musa: \"Rabbim! Göğsümü genişlet, işimi kolaylaştır, dilimin düğümünü çöz ki sözümü iyi anlasınlar. Ailemden kardeşim Harun'u bana vezir yap, beni onunla destekle, onu görevimde ortak kıl ki Seni daha çok tesbih edelim ve çokça analım. Şüphesiz Sen bizi görmektesin\" dedi.",
  "en": "[Moses] said, \"My Lord, expand [i.e., relax] for me my breast [with assurance]",
  "tafsir": "قال رب اشرح لي صدري ويسر لي أمري ) هذا سؤال من موسى ، عليه السلام ، لربه عز وجل ، أن يشرح له صدره فيما بعثه به ، فإنه قد أمره بأمر عظيم ، وخطب جسيم ، بعثه إلى أعظم ملك على وجه الأرض إذ ذاك ، وأجبرهم ، وأشدهم كفرا ، وأكثرهم جنودا ، وأعمرهم ملكا ، وأطغاهم وأبلغهم تمردا ، بلغ من أمره أن ادعى أنه لا يعرف الله ، ولا يعلم لرعاياه إلها غيره . …",
  "source_tr": "Tâhâ Sûresi, 25. âyet",
  "source_en": "Surah Taha, 20:25",
  "source_ar": "سورة طه، الآية 25"
 }
];

const DAILY_HADITHS = [
 {
  "no": 3,
  "ar": "عَنْ أَبِي عَبْدِ الرَّحْمَنِ عَبْدِ اللَّهِ بْنِ عُمَرَ بْنِ الْخَطَّابِ رَضِيَ اللَّهُ عَنْهُمَا قَالَ: سَمِعْت رَسُولَ اللَّهِ صلى الله عليه و سلم يَقُولُ: بُنِيَ الْإِسْلَامُ عَلَى خَمْسٍ: شَهَادَةِ أَنْ لَا إلَهَ إلَّا اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ، وَإِقَامِ الصَّلَاةِ، وَإِيتَاءِ الزَّكَاةِ، وَحَجِّ الْبَيْتِ، وَصَوْمِ رَمَضَانَ .",
  "en": "On the authority of Abdullah, the son of Umar ibn al-Khattab (ra), who said: I heard the Messenger of Allah (ﷺ) say, \"Islam has been built on five [pillars]: testifying that there is no deity worthy of worship except Allah and that Muhammad is the Messenger of Allah, establishing the salah (prayer), paying the zakat (obligatory charity), making the hajj (pilgrimage) to the House, and fasting in Ramadhan.\"",
  "tr": "Abdullah bin Ömer bin el-Hattab (ra) şöyle demiştir: Resulullah'ın (ﷺ) şöyle buyurduğunu işittim: \"İslam beş esas üzerine kurulmuştur: Allah’tan başka ilah olmadığına ve Muhammed’in Allah’ın elçisi olduğuna şehadet etmek, namazı kılmak, zekatı vermek, Beytullah’ı haccetmek ve Ramazan orucunu tutmak.\"",
  "source_ar": "رَوَاهُ الْبُخَارِيُّ وَمُسْلِمٌ",
  "source_en": "Bukhari & Muslim",
  "source_tr": "Buhari ve Müslim"
 },
 {
  "no": 7,
  "ar": "عَنْ أَبِي رُقَيَّةَ تَمِيمِ بْنِ أَوْسٍ الدَّارِيِّ رَضِيَ اللهُ عَنْهُ أَنَّ النَّبِيَّ صلى الله عليه وسلم قَالَ: \"الدِّينُ النَّصِيحَةُ.\" قُلْنَا: لِمَنْ؟ قَالَ: \"لِلَّهِ، وَلِكِتَابِهِ، وَلِرَسُولِهِ، وَلِأَئِمَّةِ الْمُسْلِمِينَ وَعَامَّتِهِمْ.\"",
  "en": "On the authority of Tameem ibn Aus ad-Daree (ra): The Prophet (ﷺ) said, “The deen (religion) is naseehah (advice, sincerity).” We said, “To whom?” He (ﷺ) said, “To Allah, His Book, His Messenger, and to the leaders of the Muslims and their common folk.”",
  "tr": "Temim ed-Dari (ra) anlatıyor: Peygamber (ﷺ) şöyle buyurdu: \"Din nasihattir (samimiyettir).\" Biz: \"Kime karşı?\" dedik. O (ﷺ): \"Allah’a, Kitabına, Resulü’ne, Müslümanların yöneticilerine ve tüm Müslümanlara karşı\" buyurdu.",
  "source_ar": "رَوَاهُ مُسْلِمٌ",
  "source_en": "Muslim",
  "source_tr": "Müslim"
 },
 {
  "no": 8,
  "ar": "عَنْ ابْنِ عُمَرَ رَضِيَ اللَّهُ عَنْهُمَا، أَنَّ رَسُولَ اللَّهِ صلى الله عليه و سلم قَالَ: أُمِرْتُ أَنْ أُقَاتِلَ النَّاسَ حَتَّى يَشْهَدُوا أَنْ لَا إلَهَ إلَّا اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ، وَيُقِيمُوا الصَّلَاةَ، وَيُؤْتُوا الزَّكَاةَ؛ فَإِذَا فَعَلُوا ذَلِكَ عَصَمُوا مِنِّي دِمَاءَهُمْ وَأَمْوَالَهُمْ إلَّا بِحَقِّ الْإِسْلَامِ، وَحِسَابُهُمْ عَلَى اللَّهِ تَعَالَى .",
  "en": "On the authority of Abdullah ibn Umar (ra): The Messenger of Allah (ﷺ) said, \"I have been ordered to fight against the people until they testify that there is none worthy of worship except Allah and that Muhammad is the Messenger of Allah, and until they establish the salah and pay the zakat. And if they do that then they will have gained protection from me for their lives and property, unless [they commit acts that are punishable] in Islam, and their reckoning will be with Allah.\"",
  "tr": "Abdullah bin Ömer (ra) anlatıyor: Resulullah (ﷺ) şöyle buyurdu: \"İnsanlar Allah’tan başka ilah olmadığına ve Muhammed’in O’nun elçisi olduğuna şehadet edinceye, namazı kılıp zekatı verinceye kadar onlarla savaşmakla emrolundum. Bunları yaparlarsa —İslam’ın hakkı hariç— kanlarını ve mallarını benden korumuş olurlar. Hesapları ise Allah’a aittir.\"",
  "source_ar": "رَوَاهُ الْبُخَارِيُّ وَمُسْلِمٌ",
  "source_en": "Bukhari & Muslim",
  "source_tr": "Buhari ve Müslim"
 },
 {
  "no": 9,
  "ar": "عَنْ أَبِي هُرَيْرَةَ عَبْدِ الرَّحْمَنِ بْنِ صَخْرٍ رَضِيَ اللهُ عَنْهُ قَالَ: سَمِعْت رَسُولَ اللَّهِ صلى الله عليه و سلم يَقُولُ: مَا نَهَيْتُكُمْ عَنْهُ فَاجْتَنِبُوهُ، وَمَا أَمَرْتُكُمْ بِهِ فَأْتُوا مِنْهُ مَا اسْتَطَعْتُمْ، فَإِنَّمَا أَهْلَكَ الَّذِينَ مِنْ قَبْلِكُمْ كَثْرَةُ مَسَائِلِهِمْ وَاخْتِلَافُهُمْ عَلَى أَنْبِيَائِهِمْ .",
  "en": "On the authority of Abu Hurayrah (ra): I heard the Messenger of Allah (ﷺ) say, “What I have forbidden for you, avoid. What I have ordered you [to do], do as much of it as you can. For verily, it was only the excessive questioning and their disagreeing with their Prophets that destroyed [the nations] who were before you.”",
  "tr": "Ebu Hureyre (ra) anlatıyor: Resulullah'ın (ﷺ) şöyle buyurduğunu işittim: \"Size neyi yasakladıysam ondan kaçının, neyi emrettiysem de gücünüz yettiği ölçüde onu yapın. Sizden öncekileri ancak çok soru sormaları ve peygamberlerine karşı olan ihtilafları helak etmiştir.\"",
  "source_ar": "رَوَاهُ الْبُخَارِيُّ وَمُسْلِمٌ",
  "source_en": "Bukhari & Muslim",
  "source_tr": "Buhari ve Müslim"
 },
 {
  "no": 13,
  "ar": "عَنْ أَبِي حَمْزَةَ أَنَسِ بْنِ مَالِكٍ رَضِيَ اللهُ عَنْهُ خَادِمِ رَسُولِ اللَّهِ صلى الله عليه و سلم عَنْ النَّبِيِّ صلى الله عليه و سلم قَالَ: لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ . رَوَاهُ الْبُخَارِيُّ [رقم:13]، وَمُسْلِمٌ [رقم:45].",
  "en": "On the authority of Abu Hamzah Anas bin Malik (may Allah be pleased with him) — the servant of the Messenger of Allah (peace and blessings of Allah be upon him) — that the Prophet (peace and blessings of Allah be upon him) said: None of you [truly] believes until he loves for his brother that which he loves for himself.",
  "tr": "Resulullah'ın (ﷺ) hizmetkarı Ebu Hamza Enes bin Malik (ra) anlatıyor: Peygamber (ﷺ) şöyle buyurdu: \"Sizden biriniz, kendisi için istediğini kardeşi için de istemedikçe (gerçek manada) iman etmiş olmaz.\"",
  "source_ar": "رَوَاهُ الْبُخَارِيُّ وَمُسْلِمٌ",
  "source_en": "Bukhari & Muslim",
  "source_tr": "Buhari ve Müslim"
 },
 {
  "no": 14,
  "ar": "عَنْ ابْنِ مَسْعُودٍ رَضِيَ اللهُ عَنْهُ قَالَ: قَالَ رَسُولُ اللَّهِ صلى الله عليه و سلم لَا يَحِلُّ دَمُ امْرِئٍ مُسْلِمٍ [ يشهد أن لا إله إلا الله، وأني رسول الله] إلَّا بِإِحْدَى ثَلَاثٍ: الثَّيِّبُ الزَّانِي، وَالنَّفْسُ بِالنَّفْسِ، وَالتَّارِكُ لِدِينِهِ الْمُفَارِقُ لِلْجَمَاعَةِ .",
  "en": "On the authority of Ibn Masood (may Allah be pleased with him) who said: The Messenger of Allah (peace and blessings of Allah be upon him) said, “It is not permissible to spill the blood of a Muslim except in three [instances]: the married person who commits adultery, a life for a life, and the one who forsakes his religion and separates from the community.”",
  "tr": "İbn Mes'ud (ra) anlatıyor: Resulullah (ﷺ) şöyle buyurdu: \"Müslüman bir kimsenin kanı ancak şu üç durumdan biriyle helal olur: Zina eden evli kişi, cana karşılık can (kısas) ve dinini terk edip cemaatten ayrılan kişi.\"",
  "source_ar": "رَوَاهُ الْبُخَارِيُّ وَمُسْلِمٌ",
  "source_en": "Bukhari & Muslim",
  "source_tr": "Buhari ve Müslim"
 },
 {
  "no": 15,
  "ar": "عَنْ أَبِي هُرَيْرَةَ رَضِيَ اللهُ عَنْهُ أَنَّ رَسُولَ اللَّهِ صلى الله عليه و سلم قَالَ: مَنْ كَانَ يُؤْمِنُ بِاَللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ، وَمَنْ كَانَ يُؤْمِنُ بِاَللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيُكْرِمْ جَارَهُ، وَمَنْ كَانَ يُؤْمِنُ بِاَللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيُكْرِمْ ضَيْفَهُ .",
  "en": "On the authority of Abu Hurayrah (may Allah be pleased with him), that the Messenger of Allah (peace and blessings of Allah be upon him) said: Let him who believes in Allah and the Last Day speak good, or keep silent; and let him who believes in Allah and the Last Day be generous to his neighbour; and let him who believes in Allah and the Last Day be generous to his guest.",
  "tr": "Ebu Hureyre (ra) anlatıyor: Resulullah (ﷺ) şöyle buyurdu: \"Allah’a ve ahiret gününe iman eden ya hayır söylesin ya da sussun. Allah’a ve ahiret gününe iman eden komşusuna ikram etsin. Allah’a ve ahiret gününe iman eden misafirine ikram etsin.\"",
  "source_ar": "رَوَاهُ الْبُخَارِيُّ وَمُسْلِمٌ",
  "source_en": "Bukhari & Muslim",
  "source_tr": "Buhari ve Müslim"
 },
 {
  "no": 16,
  "ar": "عَنْ أَبِي هُرَيْرَةَ رَضِيَ اللهُ عَنْهُ أَنَّ رَجُلًا قَالَ لِلنَّبِيِّ صلى الله عليه و سلم أَوْصِنِي. قَالَ: لَا تَغْضَبْ، فَرَدَّدَ مِرَارًا، قَالَ: لَا تَغْضَبْ\" .",
  "en": "On the authority of Abu Hurayrah (may Allah be pleased with him): A man said to the Prophet (peace and blessings of Allah be upon him), “Counsel me,” so he (peace and blessings of Allah be upon him) said, “Do not become angry.” The man repeated [his request for counsel] several times, and [each time] he (peace and blessings of Allah be upon him) said, “Do not become angry.”",
  "tr": "Ebu Hureyre (ra) anlatıyor: Bir adam Peygamber’e (ﷺ) \"Bana tavsiyede bulun\" dedi. Efendimiz: \"Öfkelenme\" buyurdu. Adam isteğini birkaç kez tekrarladı, Efendimiz her defasında: \"Öfkelenme\" buyurdu.",
  "source_ar": "رَوَاهُ الْبُخَارِيُّ",
  "source_en": "Bukhari",
  "source_tr": "Buhari"
 },
 {
  "no": 17,
  "ar": "عَنْ أَبِي يَعْلَى شَدَّادِ بْنِ أَوْسٍ رَضِيَ اللهُ عَنْهُ عَنْ رَسُولِ اللَّهِ صلى الله عليه و سلم قَالَ: إنَّ اللَّهَ كَتَبَ الْإِحْسَانَ عَلَى كُلِّ شَيْءٍ، فَإِذَا قَتَلْتُمْ فَأَحْسِنُوا الْقِتْلَةَ، وَإِذَا ذَبَحْتُمْ فَأَحْسِنُوا الذِّبْحَةَ، وَلْيُحِدَّ أَحَدُكُمْ شَفْرَتَهُ، وَلْيُرِحْ ذَبِيحَتَهُ .",
  "en": "On the authority of Abu Ya’la Shaddad bin Aws (may Allah be pleased with him), that the Messenger of Allah (peace and blessings of Allah be upon him) said: Verily Allah has prescribed ihsan (proficiency, perfection) in all things. So if you kill then kill well; and if you slaughter, then slaughter well. Let each one of you sharpen his blade and let him spare suffering to the animal he slaughters.”",
  "tr": "Ebu Ya’la Şeddad bin Evs (ra) anlatıyor: Resulullah (ﷺ) şöyle buyurdu: \"Allah her işte ihsanı (en güzel şekilde yapmayı) farz kılmıştır. Öldürdüğünüzde güzelce öldürün, (hayvan) kestiğinizde güzelce kesin. Her biriniz bıçağını bilesin ve keseceği hayvanı rahatlatsın.\"",
  "source_ar": "رَوَاهُ مُسْلِمٌ",
  "source_en": "Muslim",
  "source_tr": "Müslim"
 },
 {
  "no": 20,
  "ar": "عَنْ أَبِي مَسْعُودٍ عُقْبَةَ بْنِ عَمْرٍو الْأَنْصَارِيِّ الْبَدْرِيِّ رَضِيَ اللهُ عَنْهُ قَالَ: قَالَ رَسُولُ اللَّهِ صلى الله عليه و سلم إنَّ مِمَّا أَدْرَكَ النَّاسُ مِنْ كَلَامِ النُّبُوَّةِ الْأُولَى: إذَا لَمْ تَسْتَحِ فَاصْنَعْ مَا شِئْت .",
  "en": "On the authority of Abu Masood Uqbah bin ’Amr al-Ansaree al-Badree (may Allah be pleased with him) who said: The Messenger of Allah (peace and blessings of Allah be upon him) said, “Verily, from what was learnt by the people from the speech of the earliest prophecy is: If you feel no shame, then do as you wish.”",
  "tr": "Ebu Mes'ud el-Ensari (ra) anlatıyor: Resulullah (ﷺ) şöyle buyurdu: \"İnsanların peygamberlik sözlerinden ilk öğrendiği şey şudur: Şayet utanmıyorsan dilediğini yap!\"",
  "source_ar": "رَوَاهُ الْبُخَارِيُّ",
  "source_en": "Bukhari",
  "source_tr": "Buhari"
 },
 {
  "no": 21,
  "ar": "عَنْ أَبِي عَمْرٍو وَقِيلَ: أَبِي عَمْرَةَ سُفْيَانَ بْنِ عَبْدِ اللَّهِ رَضِيَ اللهُ عَنْهُ قَالَ: قُلْت: يَا رَسُولَ اللَّهِ! قُلْ لِي فِي الْإِسْلَامِ قَوْلًا لَا أَسْأَلُ عَنْهُ أَحَدًا غَيْرَك؛ قَالَ: قُلْ: آمَنْت بِاَللَّهِ ثُمَّ اسْتَقِمْ .",
  "en": "On the authority of Abu `Amr — and he is also called Abu `Amrah — Sufyan bin Abdullah ath- Thaqafee (may Allah be pleased with him) who said: I said, \"O Messenger of Allah, tell me something about al-Islam which I can ask of no one but you.\" He (peace and blessings of Allah be upon him) said, \"Say I believe in Allah — and then be steadfast.\"",
  "tr": "Ebu Amr Süfyan bin Abdullah (ra) anlatıyor: \"Ey Allah’ın Resulü! Bana İslam hakkında öyle bir söz söyle ki, senden sonra başka kimseye sormaya ihtiyacım kalmasın\" dedim. Şöyle buyurdu: \"Allah’a inandım de, sonra da dosdoğru ol!\"",
  "source_ar": "رَوَاهُ مُسْلِمٌ",
  "source_en": "Muslim",
  "source_tr": "Müslim"
 },
 {
  "no": 22,
  "ar": "عَنْ أَبِي عَبْدِ اللَّهِ جَابِرِ بْنِ عَبْدِ اللَّهِ الْأَنْصَارِيِّ رَضِيَ اللَّهُ عَنْهُمَا: أَنَّ رَجُلًا سَأَلَ رَسُولَ اللَّهِ صلى الله عليه و سلم فَقَالَ: أَرَأَيْت إذَا صَلَّيْت الْمَكْتُوبَاتِ، وَصُمْت رَمَضَانَ، وَأَحْلَلْت الْحَلَالَ، وَحَرَّمْت الْحَرَامَ، وَلَمْ أَزِدْ عَلَى ذَلِكَ شَيْئًا؛ أَأَدْخُلُ الْجَنَّةَ؟ قَالَ: نَعَمْ .",
  "en": "On the authority of Abu Abdullah Jabir bin Abdullah al-Ansaree (may Allah be pleased with him) that: A man questioned the Messenger of Allah (peace and blessings of Allah be upon him) and said, “Do you think that if I perform the obligatory prayers, fast in Ramadhan, treat as lawful that which is halal, and treat as forbidden that which is haram, and do not increase upon that [in voluntary good deeds], then I shall enter Paradise?” He (peace and blessings of Allah be upon him) replied, “Yes.”",
  "tr": "Ebu Abdullah Cabir bin Abdullah el-Ensari (ra) anlatıyor: Bir adam Resulullah’a (ﷺ) sordu: \"Ne dersin; farz namazları kılsam, Ramazan orucunu tutsam, helali helal bilip haramı haram saysam ve bunlara hiçbir şey eklemesem cennete girer miyim?\" Efendimiz: \"Evet\" buyurdu.",
  "source_ar": "رَوَاهُ مُسْلِمٌ",
  "source_en": "Muslim",
  "source_tr": "Müslim"
 },
 {
  "no": 23,
  "ar": "عَنْ أَبِي مَالِكٍ الْحَارِثِ بْنِ عَاصِمٍ الْأَشْعَرِيِّ رَضِيَ اللهُ عَنْهُ قَالَ: قَالَ رَسُولُ اللَّهِ صلى الله عليه و سلم الطَّهُورُ شَطْرُ الْإِيمَانِ، وَالْحَمْدُ لِلَّهِ تَمْلَأُ الْمِيزَانَ، وَسُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ تَمْلَآنِ -أَوْ: تَمْلَأُ- مَا بَيْنَ السَّمَاءِ وَالْأَرْضِ، وَالصَّلَاةُ نُورٌ، وَالصَّدَقَةُ بُرْهَانٌ، وَالصَّبْرُ ضِيَاءٌ، وَالْقُرْآنُ حُجَّةٌ لَك أَوْ عَلَيْك، كُلُّ النَّاسِ يَغْدُو، فَبَائِعٌ نَفْسَهُ فَمُعْتِقُهَا أَوْ مُوبِقُهَا .",
  "en": "On the authority of Abu Malik al-Harith bin Asim al-Asharee (may Allah be pleased with him) who said: The Messenger of Allah (peace and blessings of Allah be upon him) said, “Purity is half of iman (faith). ‘Al-hamdu lillah (praise be to Allah)’ fills the scales, and ‘subhan-Allah (how far is Allah from every imperfection) and ‘Al-hamdulillah (praise be to Allah)’ fill that which is between heaven and earth. And the salah (prayer) is a light, and charity is a proof, and patience is illumination, and the Qur’an is a proof either for you or against you. Every person starts his day as a vendor of his soul, either freeing it or causing its ruin.”",
  "tr": "Ebu Malik el-Eş’ari (ra) anlatıyor: Resulullah (ﷺ) şöyle buyurdu: \"Temizlik imanın yarısıdır. 'Elhamdülillah' mizanı doldurur. 'Sübhanallahi ve’l-hamdülillahi' ise göklerle yer arasını doldurur. Namaz bir nurdur, sadaka bir burhandır (delildir), sabır bir ziyadır (ışıktır). Kur’an ise ya lehine ya da aleyhine bir delildir. Herkes sabah kalkar ve nefsini satar; kimisi onu azat eder, kimisi de helak eder.\"",
  "source_ar": "رَوَاهُ مُسْلِمٌ",
  "source_en": "Muslim",
  "source_tr": "Müslim"
 },
 {
  "no": 26,
  "ar": "عَنْ أَبِي هُرَيْرَةَ رَضِيَ اللهُ عَنْهُ قَالَ: قَالَ رَسُولُ اللَّهِ صلى الله عليه و سلم كُلُّ سُلَامَى مِنْ النَّاسِ عَلَيْهِ صَدَقَةٌ، كُلَّ يَوْمٍ تَطْلُعُ فِيهِ الشَّمْسُ تَعْدِلُ بَيْنَ اثْنَيْنِ صَدَقَةٌ، وَتُعِينُ الرَّجُلَ فِي دَابَّتِهِ فَتَحْمِلُهُ عَلَيْهَا أَوْ تَرْفَعُ لَهُ عَلَيْهَا مَتَاعَهُ صَدَقَةٌ، وَالْكَلِمَةُ الطَّيِّبَةُ صَدَقَةٌ، وَبِكُلِّ خُطْوَةٍ تَمْشِيهَا إلَى الصَّلَاةِ صَدَقَةٌ، وَتُمِيطُ الْأَذَى عَنْ الطَّرِيقِ صَدَقَةٌ .",
  "en": "On the authority of Abu Hurayrah (may Allah be pleased with him) who said: The Messenger of Allah (peace and blessings of Allah be upon him) said, “Every joint of a person must perform a charity each day that the sun rises: to judge justly between two people is a charity. To help a man with his mount, lifting him onto it or hoisting up his belongings onto it, is a charity. And the good word is a charity. And every step that you take towards the prayer is a charity, and removing a harmful object from the road is a charity.”",
  "tr": "Ebu Hureyre (ra) anlatıyor: Resulullah (ﷺ) şöyle buyurdu: \"Güneşin doğduğu her gün, insanın her bir eklemi (mafsalı) için bir sadaka borcu vardır: İki kişinin arasını adaletle düzeltmek sadakadır. Birine hayvanına binmesi veya yükünü taşıması için yardım etmek sadakadır. Güzel söz sadakadır. Namaza gitmek için atılan her adım sadakadır. Yoldaki rahatsızlık veren şeyi kaldırmak sadakadır.\"",
  "source_ar": "رَوَاهُ الْبُخَارِيُّ وَمُسْلِمٌ",
  "source_en": "Bukhari & Muslim",
  "source_tr": "Buhari ve Müslim"
 },
 {
  "no": 34,
  "ar": "عَنْ أَبِي سَعِيدٍ الْخُدْرِيّ رَضِيَ اللهُ عَنْهُ قَالَ سَمِعْت رَسُولَ اللَّهِ صلى الله عليه و سلم يَقُولُ: مَنْ رَأَى مِنْكُمْ مُنْكَرًا فَلْيُغَيِّرْهُ بِيَدِهِ، فَإِنْ لَمْ يَسْتَطِعْ فَبِلِسَانِهِ، فَإِنْ لَمْ يَسْتَطِعْ فَبِقَلْبِهِ، وَذَلِكَ أَضْعَفُ الْإِيمَانِ .",
  "en": "On the authority of Abu Sa`eed al-Khudree (may Allah be pleased with him) who said: I heard the Messenger of Allah (ﷺ) say, “Whosoever of you sees an evil, let him change it with his hand; and if he is not able to do so, then [let him change it] with his tongue; and if he is not able to do so, then with his heart — and that is the weakest of faith.”",
  "tr": "Ebu Said el-Hudri (ra) anlatıyor: Resulullah'ın (ﷺ) şöyle buyurduğunu işittim: \"Sizden kim bir kötülük görürse onu eliyle düzeltsin; buna gücü yetmezse diliyle düzeltsin; buna da gücü yetmezse kalbiyle buğz etsin ki bu imanın en zayıf derecesidir.\"",
  "source_ar": "رَوَاهُ مُسْلِمٌ",
  "source_en": "Muslim",
  "source_tr": "Müslim"
 },
 {
  "no": 40,
  "ar": "عَنْ ابْن عُمَرَ رَضِيَ اللَّهُ عَنْهُمَا قَالَ: أَخَذَ رَسُولُ اللَّهِ صلى الله عليه و سلم بِمَنْكِبِي، وَقَالَ: كُنْ فِي الدُّنْيَا كَأَنَّك غَرِيبٌ أَوْ عَابِرُ سَبِيلٍ . وَكَانَ ابْنُ عُمَرَ رَضِيَ اللَّهُ عَنْهُمَا يَقُولُ: إذَا أَمْسَيْتَ فَلَا تَنْتَظِرْ الصَّبَاحَ، وَإِذَا أَصْبَحْتَ فَلَا تَنْتَظِرْ الْمَسَاءَ، وَخُذْ مِنْ صِحَّتِك لِمَرَضِك، وَمِنْ حَيَاتِك لِمَوْتِك.",
  "en": "On the authority of Abdullah ibn Umar (may Allah be pleased with him), who said: The Messenger of Allah (peace and blessings of Allah be upon him) took me by the shoulder and said, “Be in this world as though you were a stranger or a wayfarer.” And Ibn Umar (may Allah be pleased with him) used to say, “In the evening do not expect [to live until] the morning, and in the morning do not expect [to live until] the evening. Take [advantage of] your health before times of sickness, and [take advantage of] your life before your death.”",
  "tr": "Abdullah bin Ömer (ra) anlatıyor: Resulullah (ﷺ) omzumdan tuttu ve şöyle buyurdu: \"Dünyada tıpkı bir yabancı veya bir yolcu gibi ol.\" İbn Ömer (ra) şöyle derdi: \"Akşama erdiğinde sabahı bekleme, sabaha erdiğinde de akşamı bekleme. Sağlıklı olduğun zaman hastalık halin için, hayatın boyunca da ölümün için hazırlık yap.\"",
  "source_ar": "رَوَاهُ الْبُخَارِيُّ",
  "source_en": "Bukhari",
  "source_tr": "Buhari"
 }
];
